/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CommitteeOnlyRouteImport } from './routes/committee-only'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as DurgaPujaRouteImport } from './routes/durga-puja'
import { Route as EventsRouteImport } from './routes/events'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as KaliBariRouteImport } from './routes/kali-bari'
import { Route as SponsorsRouteImport } from './routes/sponsors'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteeOnlyRoute = CommitteeOnlyRouteImport.update({
  id: '/committee-only',
  path: '/committee-only',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const DurgaPujaRoute = DurgaPujaRouteImport.update({
  id: '/durga-puja',
  path: '/durga-puja',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const KaliBariRoute = KaliBariRouteImport.update({
  id: '/kali-bari',
  path: '/kali-bari',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/committee-only': typeof CommitteeOnlyRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/durga-puja': typeof DurgaPujaRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/kali-bari': typeof KaliBariRoute
  '/sponsors': typeof SponsorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/committee-only': typeof CommitteeOnlyRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/durga-puja': typeof DurgaPujaRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/kali-bari': typeof KaliBariRoute
  '/sponsors': typeof SponsorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/committee-only': typeof CommitteeOnlyRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/durga-puja': typeof DurgaPujaRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/kali-bari': typeof KaliBariRoute
  '/sponsors': typeof SponsorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/committee-only'
    | '/contact'
    | '/donate'
    | '/durga-puja'
    | '/events'
    | '/gallery'
    | '/kali-bari'
    | '/sponsors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/committee-only'
    | '/contact'
    | '/donate'
    | '/durga-puja'
    | '/events'
    | '/gallery'
    | '/kali-bari'
    | '/sponsors'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/committee-only'
    | '/contact'
    | '/donate'
    | '/durga-puja'
    | '/events'
    | '/gallery'
    | '/kali-bari'
    | '/sponsors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommitteeOnlyRoute: typeof CommitteeOnlyRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  DurgaPujaRoute: typeof DurgaPujaRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  KaliBariRoute: typeof KaliBariRoute
  SponsorsRoute: typeof SponsorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committee-only': {
      id: '/committee-only'
      path: '/committee-only'
      fullPath: '/committee-only'
      preLoaderRoute: typeof CommitteeOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/durga-puja': {
      id: '/durga-puja'
      path: '/durga-puja'
      fullPath: '/durga-puja'
      preLoaderRoute: typeof DurgaPujaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kali-bari': {
      id: '/kali-bari'
      path: '/kali-bari'
      fullPath: '/kali-bari'
      preLoaderRoute: typeof KaliBariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommitteeOnlyRoute: CommitteeOnlyRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  DurgaPujaRoute: DurgaPujaRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  KaliBariRoute: KaliBariRoute,
  SponsorsRoute: SponsorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
